### ISSUE TITLE
Saving Car Paint

### ISSUE THREAD

**Issue by beauflexx** [BryanDevelopes/esx-chameleonpaint#1]
Store vehicle at a garage, the paint does not save after calling the vehicle out. 

Do i need to set anything up on the es_extended config?

**Comment by BJDevelopes** [comment]
I havent actually setup vehicle saving yet, let me look into this and see what I can do. I will try to issue an update to this tonight

**Comment by BJDevelopes** [comment]
Update has been made, see the options in the Config file. Set garage saving to true 😄
